### ISSUE TITLE
Proper build step

### ISSUE THREAD

**Issue by Markionium** [dhis2/settings-app#12]
The current building of the app for prod is too complicated and requires too much manual effort.

**Comment by nicolayr** [comment]
I've been thinking about how to solve this, but I don't know Maven well enough to say what the best solution is.

I can think of two options that might work:

1. Make a simple npm script that copies the app to the appropriate bzr folder after build
2. Publish "compiled" versions to github and have Maven download the latest one during build

Of these, I prefer the 1st option because it gives us more control over versioning.

**Comment by Markionium** [comment]
Yeah that is still a think we need to solve. I just _solved_ the issue of having a prod and a master branch. From now on i guess we can do with one branch only. As cherry-picking commits from one to the other etc seemed a bit silly.

I'll update the readme for future reference of whoever joins us on this.

**Comment by nicolayr** [comment]
This is now solved by publishing "compiled" versions of the app to a Maven repo using `mvn deploy`.
