### ISSUE TITLE
Something funky with translations

### ISSUE THREAD

**Issue by Markionium** [dhis2/settings-app#69]
The `HeaderBar` component should do most of the registrations of the strings it needs to translate. 

Like for the profile app part of the dropdown menu
https://github.com/dhis2/d2-ui/blob/7a13320220e0ff0ef2a9f26ca366f6c478e69df1/src/app-header/menu-sources.js#L6-L11

Separately registering these strings should therefore not be necessary like we do here in
https://github.com/dhis2/settings-app/blob/master/src/settings-app.js#L169-L177

I haven't looked into why this happens. Perhaps the way we register strings in the settings app overwrites the previously registered ones?

It's not really urgent, but might be good to unify :) (Perhaps this could be part of the larger i18n work)

**Comment by nicolayr** [comment]
The root cause of these problems was the fact that the header bar component used the D2 config to load translations during initialisation, while the settings app explicitly loaded translations after initialising D2. Fixed it in f8fa2d88aaf42c0fa613685b6cb154a38f81b0b3 by loading all translations during D2 init.
