### ISSUE TITLE
i18n Issues

### ISSUE THREAD

**Issue by jason-p-pickering** [dhis2/settings-app#74]
Unit: https://translate.dhis2.org/en/settings-app/translate/en.po#unit=760447
Source: Object not deleted because it is associated by objects of type
Current translation: Object not deleted because it is associated by objects of type
Your question or comment:
I am concerned that this string should have a placeable (%s) at the end to allow proper contextual translation outside of subject-verb-object (SVO) order grammars.

**Comment by Markionium** [comment]
This is related to some more deeper issue with how to translate messages that are returned from the api.

The key you refer to (`object_not_deleted_associated_by_objects`) is not used in the app and is probably in there due to some copy paste work from older `.properties` files. (Same goes for the maintenance-app, which contains the same key)

**Comment by jason-p-pickering** [comment]
It seems there are a large number of these. Perhaps the real issue is to clean out the unneeded keys?

**Comment by Markionium** [comment]
In this case yes, but the "new" keys that are supposed to replace these should probably have the %s. As currently these messages (if i remember correctly) are never translated, the ones that come straight from the api.

**Comment by nicolayr** [comment]
This is an issue that should probably be addressed on a more general level (ie. in D2-UI), so I'm closing this one.
